### ISSUE TITLE
Make possible to replace HEX i binary file

### ISSUE THREAD

**Issue by jonas18z** [adamreisnz/replace-in-file#10]
Is it possible to make this to find and replace HEX-value in a binary file?

**Comment by adamreisnz** [comment]
Currently I don't think this is possible, but I can investigate what would be involved to add support for it.

**Comment by adamreisnz** [comment]
I've had another look, but due to the complications involved with handling binary data properly, I think this is beyond the scope of this package. I don't want to unnecessarily bloat this package with other dependencies if I can avoid it.

You might want to look in https://github.com/marvinroger/node-binary-file which could probably be useful for your use case.

If you find a solution that is light weight, feel free to share and re-open this issue and I'll see if we could add it in.
