### ISSUE TITLE
Replacing misses straight quote

### ISSUE THREAD

**Issue by kolomu** [adamreisnz/replace-in-file#106]
When replacing values with single quotes they are getting lost.

Here is an example:
```javascript
var config = [
  {
    "name": "\"assets/my-picture.jpg\"",
    "toReplace": "'$MEDIA(ref:\"my_picture\")$'"
  }
]

const replace = require('replace-in-file');

const options = {
  files: 'test-file.js',
  from: /foo/g,
  to: 'bar',
};

try {
  for (let i = 0; i < config.length; i++) {
    console.log("Replacing: " + config[i].name + " to:\t" + config[i]['toReplace']);
    options.from = config[i].name;
    options.to = config[i]['toReplace'];
    replace.sync(options);
  }
} catch (error) {
  console.error('Error occurred: ', error);
}
```

Then create another file called "test-file.js" with the following content:
```javascript
var myTest = ["src","assets/my-picture.jpg"];
```

Run the script and the result will be:
```javascript
var myTest = ["src",'$MEDIA(ref:"my_picture")];

];
```

But expected is: 
```
var myTest = ["src",'$MEDIA(ref:"my_picture")$'];
```

Did I do something wrong? Maybe JSON is not the best method to handle replacement strings but I thought it should work like this.

Best Regards

**Comment by adamreisnz** [comment]
Did you end up solving this? It looks like your example is a bit messy, with the replacement `/foo/g` from the readme still in there.

Why is the config file using `name` instead of `from`?

Replace in file uses simply [String.prototype.replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) under the hood, have you verified your regex works properly using that method?

**Comment by kolomu** [comment]
My mistake thank for your hint
