### ISSUE TITLE
CLI only replacing first ocurrence

### ISSUE THREAD

**Issue by DavidBiesack** [adamreisnz/replace-in-file#110]
When using the CLI, only the first occurrence of the pattern is matched/replaced:

```
$ cat /tmp/test.txt
abc
abc
abc
abc
$ replace-in-file abc ABC /tmp/test.txt 
Replacing 'abc' with 'ABC'
1 file(s) were changed
$ cat /tmp/test.txt
ABC
abc
abc
abc
```

I'm running 5.0.2:

```
$ replace-in-file --version
5.0.2
```

**Comment by DavidBiesack** [comment]
I was able to make this work with 
```
replace-in-file /abc/g ABC /tmp/test.txt  --isRegex
```

but I think global replacement should be the default for the CLI.

Also note that the `--help` option does not describe all the CLI options:

```
replace-in-file --help
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```

**Comment by adamreisnz** [comment]
I'm not sure where those help messages are coming from, might be the defaults from yargs. I never implemented it, but PR is welcome. The readme should contain all available CLI options.

**Comment by adamreisnz** [comment]
PS: It's not very practical to make the CLI use a global flag by default, and it could be awkward if people _don't_ want the default flag. How would we then remove it?

Plus, I am reluctant to change default behaviour because it may lead to unexpected results for people used to this behaviour. The default regex behaviour is also not global by default.

**Comment by adamreisnz** [comment]
Will actually close this now as it has been resolved, but feel free to raise another issue for the `--help` option or create a PR for it.
