### ISSUE TITLE
File paths starting with dot are skipped

### ISSUE THREAD

**Issue by k2snowman69** [adamreisnz/replace-in-file#133]
Reproduction:
1. Create a new empty directory named `example`
2. Create a file`.test` in the new directory with the text `coverage` inside of it
2. Run `npx replace-in-file "coverage" "coverage-2" example/**`

Expected:
One file to be changed

Actual:
No files were changed

Current workaround:
Explicitly add dot files into the command
`npx replace-in-file "coverage" "coverage-2" example/**,example/**/.*`

**Comment by adamreisnz** [comment]
I suspect that is how glob works, as we use glob to match files for us.
You can probably specify glob configuration to address this, see:

https://github.com/adamreisnz/replace-in-file#specify-glob-configuration

Or your work around, as mentioned. Let me know if you think the problem lies with the package instead of glob.

**Comment by k2snowman69** [comment]
I'm embarrassed I didn't think of that. Thanks! Looks like the particular setting is likely 
```
dot:true
```

**Comment by adamreisnz** [comment]
Yes that's the one, no worries 👍
