### ISSUE TITLE
ENAMETOOLONG error Github actions

### ISSUE THREAD

**Issue by UVLabs** [adamreisnz/replace-in-file#137]
We use this repo as an NPM package with https://github.com/semantic-release/semantic-release and tried implementing it into our Github actions workflow and there seem to be an issue with doing the replacement.

The job ([see here](https://github.com/Codeinwp/tweet-old-post/runs/2766869494?check_suite_focus=true#step:4:494)) seems to fail with the error ENAMETOOLONG. My hunch is that the script gets confused because of the double quotes in the commit message around **Share Content**: https://github.com/Codeinwp/tweet-old-post/commit/fc0156f1e36b123303b1a1a059096ec81322a48f

`[New Pro] Post Format "Share Content" option to share post's Yoast SEO title or description.`

Error: `Error: ENAMETOOLONG: name too long, open 'Content option to share post's Yoast SEO title or description.`

This causes the Github actions job to fail and we had to stop calling the script so the job can pass. You can see how the script is being called here:

https://github.com/Codeinwp/tweet-old-post/blob/master/.releaserc.yml#L12

How can we prevent replace-in-file from choking when it gets to the quotes?

**Comment by adamreisnz** [comment]
Hi there, that is not an error that is thrown by `replace-in-file`, so I'm not sure how to help with this one. If you think the quotes may cause problems, perhaps there is a way to escape them first before passing it as a CLI argument? You could also consider wrapping the replace-in-file command in another script, so that you can call it programmatically and not via CLI (you'd call your own script via CLI).
