### ISSUE TITLE
countMatches not working with async replace & processor

### ISSUE THREAD

**Issue by elijaholmos** [adamreisnz/replace-in-file#147]
My implementation is as follows:
```js
import replace from "replace-in-file";

const results = await replace.replaceInFile({
    files: './src/main/resources/templates/*.html',
    countMatches: true,
    dry: true,
    processor: (input) => 
        input.split('\r\n').map(line => {
            //add th reference
            if(line.includes('<html>'))
                line = line.replace('<html>', '<html xmlns:th="http://www.thymeleaf.org">');
            //non html hrefs
            if(line.includes(`href="assets`)) {
                const path = line.split('href="').pop().split(`"`).shift();
                line = line.replace('href', 'th:href').replace(path, `@{/${path.replace('.html', '')}}`)
            }
            //src attrs
            if(line.includes(`src="assets`)) {
                const path = line.split('src="').pop().split(`"`).shift();
                line = line.replace('src', 'th:src').replace(path, `@{/${path}}`)
            }
            return line;
        }).join('\r\n'),
});

console.log(results);
```

I have tried both a dry and wet run, but the `results` array only includes objects with `file` and `hasChanged`, no `numMatches` or `numReplacements`. As a side note, I tried a synchronous operation but that failed entirely. Something related to `ReferenceError: processFileSync is not defined`. I can provide more info on that if requested.

Node v16.6.0
NPM v7.19.1
replace-in-file v6.31

**Comment by adamreisnz** [comment]
Sorry I don't see what is wrong with that line, other than it has a superfluous callback param.

**Comment by m4ttheweric** [comment]
So I can chime in and say I am getting a ReferenceError due to the `cb` param. See my terminal output:
![Screen Shot 2021-11-04 at 12 28 31 PM](https://user-images.githubusercontent.com/49927862/140407038-b7bd9544-6546-49d3-8b81-f7f433160585.png)

I am using the `replaceInFileSync()` function with the `files` param and the `processor` function param.

 I am running it in a typescript project and have to tell the TS processor to ignore the `processor` prop or it gets angry since the `processor` prop doesn't exist on the `ReplaceInFileConfig` interface.

**Comment by m4ttheweric** [comment]
As a follow up, if i use `replaceInFile()` rather than `replaceInFileSync()` the error does not occur.

**Comment by adamreisnz** [comment]
This should be fixed
