### ISSUE TITLE
Custom replacer function or option

### ISSUE THREAD

**Issue by niksmac** [adamreisnz/replace-in-file#70]
I was trying this out for one of my project where I want to find a match in line and `delete` the whole line itself. Is it possible? 
If not, it think it would be a great addition if you do. 

Here is what I end up doing.

```
const domain = 'google.com'
const regex = new RegExp(`.*\\b(${domain})\\b.*`, 'gi');
const options = {
      files: 'my/path/',
      from: regex,
      to: ''
};

```

Then I am replacing all empty lines with another module.

**Comment by adamreisnz** [comment]
Well, if you include the newline itself in your regex, it should remove that too.

So while you can't say "delete this line if you find a match", you can manipulate the regex so that it includes the newline with the match you're trying to find, and then replace it with an empty string. Let me know how you go.

**Comment by niksmac** [comment]
Cool I got it working when I tried this

```
new RegExp(.*\\b(${domain})\\b.*\n, 'gi');
```
