### ISSUE TITLE
Enhancement: Please add option flag to allow return of only changed files

### ISSUE THREAD

**Issue by TotallyInformation** [adamreisnz/replace-in-file#75]
The old method was much simpler for me.

Here I merge 3 partial files to a single html file for a tool that uses some non-standard tags:

```
function mergehtml() {
    // nodes\lib\uibuilder-help.html
    const myhelp = fs.readFileSync('./node-src/uibuilder-help.html')
    const mytemplate = fs.readFileSync('./node-src/uibuilder-template.html')
    const myscript = fs.readFileSync('./node-src/uibuilder-script.js')

    // Copy template
    fs.copyFileSync('./node-src/uibuilder.html', './nodes/uibuilder.html')

    var options = {
        files: './nodes/uibuilder.html',
        from: [
            /(<script type="text\/javascript">)(.|\n)*?(<\/script>)/gmi,
            /(<script type="text\/x-red" data-template-name="uibuilder">)(.|\n)*?(<\/script>)/gmi,
            /(<script type="text\/x-red" data-help-name="uibuilder">)(.|\n)*?(<\/script>)/gmi,
        ],
        to: [
            `$1\n${myscript}\n$3`,
            `$1\n${mytemplate}\n$3`,
            `$1\n${myhelp}\n$3`,
        ],
    }

    replace(options)
        .then(changes => {
            console.log('MERGEHELP: Modified files:', changes.join(', '))
            restartNR()
        })
        .catch(error => {
            console.error('MERGEHELP: Error occurred:', error)
        })

    console.log('MERGEHELP: Completed')
}
```

I call this from a file watch tool so that the final file is always up-to-date. I don't really want to make this more complex with filters and maps please!

**Comment by adamreisnz** [comment]
This change is documented in the [readme](https://github.com/adamreisnz/replace-in-file#return-value) as well as the [change log](https://github.com/adamreisnz/replace-in-file/blob/master/CHANGELOG.md).

It's really not that complicated to add a single filter and map to get the data you need:

```js
const changedFiles = results.filter(result => result.hasChanged).map(result => result.file);
```

You can still use version 3.x.x if you want to avoid filter/map, but I don't really see a reason why you should.

This tool is moving forward and as people use it for more purposes, we've had to change the data format that gets returned to accommodate for these use cases.

No plans at this stage to add a flag to change the output data format, since the data you're after is still there – you just need a slightly different approach to recover it 😃

**Comment by adamreisnz** [comment]
PS: I'll even write out the code for you in your example:

```js
replace(options)
        .then(results => {
            const changes = results.filter(result => result.hasChanged).map(result => result.file);
            console.log('MERGEHELP: Modified files:', changes.join(', '))
            restartNR()
        })
        .catch(error => {
            console.error('MERGEHELP: Error occurred:', error)
        })
```

**Comment by TotallyInformation** [comment]
OK, it is your library - this was just a suggestion that might make things easier for a few people.

Thanks for the code.
