### ISSUE TITLE
Double quotes in arguments

### ISSUE THREAD

**Issue by niklausburren** [adamreisnz/replace-in-file#76]
I have the following script in package.json file:
`"build:prod:fr": "ng build --configuration=prod-de && replace-in-file lang=\"de\" lang=\"fr\" dist/dashboard/fr/index.html"`

When I run the script the double quotes in the arguments are alway removed:

`Replacing 'lang=de' with 'lang=fr'`
`No files were changed`

**Comment by adamreisnz** [comment]
Hi there, can you show me your exact configuration, as well as the contents of the file before and after the script has run?

**Comment by niklausburren** [comment]
Hi, thanks for your reply.

There is no other configuration than the params that I pass in the cli:

`replace-in-file lang=\"de\" lang=\"fr\" dist/dashboard/fr/index.html` 

The problem is that double quotes in the values for the params `from` and `to` are always removed. As the output is showing `replace-in-file` is searching for `lang=de` instead of `lang="de"`. For this reason no match is found and nothing is replaced in the file.

For example when I run `replace-in-file` with the following parameters the language in the file is replaced.

`replace-in-file de fr dist/dashboard/fr/index.html` 

But I want to have a more specific search pattern to avoid false replacements.

Have you an idea why the double quotes are removed. You can easily reproduce this by simply placing a double quote in the values for the `from` and `to` parameters

**Comment by adamreisnz** [comment]
Ok thanks, I will investigate this tomorrow.

**Comment by adamreisnz** [comment]
I'm afraid I'm not running into any issues with this replacement on OS X, maybe it's something to do with how windows handles quotes around CLI arguments.

Test HTML file:
```html
<html lang="de">
```

CLI command:
```
replace-in-file lang=\"de\" lang=\"fr\" test.html
Replacing 'lang="de"' with 'lang="fr"'
1 file(s) were changed
```

Output:
```html
<html lang="fr">
```

Perhaps you need double escaping or another trick to preserve the quotes from reaching replace-in-file. Otherwise, you can also always use a configuration file to accomplish the replacement, which in my opinion would be preferred anyway as then you can do a truly global replacement with the `/g` flag:

replace-in-file.config.fr.js:

```js
module.exports = {
  from: /lang="de"/g,
  to: 'lang="fr"',
};
```

CLI command:

```
replace-in-file test.html --configFile replace-in-file.config.fr.js
Replacing '/lang="de"/g' with 'lang="fr"'
1 file(s) were changed
```

You can put together different config files per language if needed, and this should bypass the quotes problem in CLI.

**Comment by niklausburren** [comment]
Thank you for your investigation and the tip with the config file.
